import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Waqar Hussain - Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          position="bottom-right"
          richColors
          toastOptions={{
            classNames: {
              toast:
                "rounded-lg border px-4 py-3 shadow-md flex items-start gap-3 w-full max-w-sm bg-[#F6FFF9] border-[#48C1B5] text-[#2F3F53] font-[400]",
              title: "text-[#27303A] font-[600]",
              description: "text-[14px] text-[#2F3F53]",
              actionButton: "bg-transparent text-[#48C1B5]",
              cancelButton: "text-[#979FA9]",
              closeButton: "text-[#979FA9] hover:text-black",
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
